name: Resume PDF Build

on:
  push:
    branches: [ "main" ]
    # paths: [ 'resume.tex' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install LaTeX
      run: sudo apt-get update && sudo apt-get install -y texlive-latex-base
      
    - name: Install pdflatex
      run: sudo apt-get update && sudo apt-get install -y pdflatex

    - name: Make resume
      run: make

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: resume-pdf
        path: resume.pdf

